apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          command:
            - /usr/local/bin/argocd-server
          args:
            - --staticassets
            - /shared/app
            - --insecure
