on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Choose environment to install ArgoCD
name: Install ArgoCD
jobs:
  deploy:
    name: Install ArgoCD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Install ArgoCD
      uses: myrotvorets/kubectl-action@2.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
      with:
        args: apply -k argocd-install/
    # - name: verify deployment
    #   uses: ghostzero/kubectl@v1
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #     KUBECTL_VERSION: "1.15"
    #   with:
    #     args: '"rollout status deployment/my-app"'